sudo: required

language: go

go:
  - master

before_install:
  # install goveralls
  - go get github.com/mattn/goveralls
  - go get github.com/verygoodsoftwarenotvirus/tarp

script:
  # unit tests
  - go test -v -coverprofile=coverage.out
  - tarp analyze --fail-on-found

after_success:
  # send coverage report to coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  # yuge thanks to this blog post: https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
  # I'm only doing pre-alpha tags for the moment, but if I were doing versioned tags, it might look something like this:
  #   - export TAG=`if [ `git rev-parse --abbrev-ref HEAD` = "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # - if [ `git rev-parse --abbrev-ref HEAD` = "master" ]; then
  - docker build --no-cache --tag verygoodsoftwarenotvirus/tarp:latest .;
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push verygoodsoftwarenotvirus/tarp:latest;
    # fi