sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

before_install:
  # install goveralls
  - go get github.com/mattn/goveralls
  - go install

script:
  # unit tests
  - docker build -t tarp_test -f test.Dockerfile .
  - docker run --name tarp_test --rm tarp_test
  - tarp analyze --fail-on-found

# after_success:
#   # send coverage report to coveralls
#   - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
