sudo: required

language: go

go:
  - master

before_install:
  # install goveralls
  - go get github.com/mattn/goveralls
  - go get github.com/verygoodsoftwarenotvirus/tarp

script:
  # unit tests
  - go test -coverprofile=coverage.out
  - tarp analyze --fail-on-found

after_success:
  # send coverage report to coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN